- id: '1668465104974'
  alias: Notis vid dåligt batteri
  description: Skicka ut en notifikation när sensorer har dåligt batteri.
  use_blueprint:
    path: gmlupatelli/low_battery_notification.yaml
    input:
      threshold: 15
      actions:
      - service: notify.mobile_app_albin_iphone
        data:
          title: Dåligt batteri
          message: '{{sensors}} har under 15% batterinivå'
      time: 09:00:00
      exclude:
        entity_id:
        - sensor.matilda_iphone_app_battery_level
        - sensor.albin_iphone_app_battery_level
        - sensor.albin_macbook_battery_level
- id: '1674327218081'
  alias: Kontroll Garderob
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      integration: ZHA
      controller_device: cad760edc13796a74f8e34fc25c2866d
      action_button_up_short:
      - service: light.turn_on
        target:
          entity_id: light.wardrobe_lamp_bedroom
      action_button_down_short:
      - service: light.turn_off
        target:
          entity_id: light.wardrobe_lamp_bedroom
      action_button_up_long:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          entity_id: light.wardrobe_lamp_bedroom
      action_button_down_long:
      - service: light.turn_on
        data:
          brightness_pct: 30
        target:
          entity_id: light.wardrobe_lamp_bedroom
      helper_last_controller_event: input_text.controller_helper_wardrobe
- id: cef76b99-053d-407a-afac-50272f7a2c08
  alias: Kontroll Uterum
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      controller_device: 05cdc0b96bd5f7257dfc4affb730767e
      integration: ZHA
      helper_last_controller_event: input_text.controller_helper_conservatory
      action_button_up_short:
      - service: light.turn_on
        target:
          entity_id:
          - light.lamp_conservatory
          - light.roof_loop_conservatory
        alias: Sätt på Takslinga och Lampa
      action_button_up_long:
      - service: switch.turn_on
        target:
          entity_id: switch.airfryer_conservatory
        alias: Sätt på AirFryer
      action_button_down_short:
      - service: light.turn_off
        target:
          entity_id:
          - light.lamp_conservatory
          - light.roof_loop_conservatory
        alias: Stäng av Takslinga och Lampa
      action_button_down_long:
      - service: switch.turn_off
        target:
          entity_id: switch.airfryer_conservatory
        alias: Stäng av AirFryer
- id: '1674415459296'
  alias: Kontroll Albin Sovrum
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      integration: ZHA
      controller_device: 30b46d58ca3ede7ea1e1e0298f001601
      helper_last_controller_event: input_text.controller_helper_albin_bedroom
      action_button_up_short: []
      action_button_up_long:
      - service: scene.turn_on
        target:
          entity_id: scene.night
        metadata: {}
      action_button_up_double:
      - service: media_player.toggle
        data: {}
        target:
          entity_id: media_player.tv_bedroom
      action_button_down_short:
      - type: turn_on
        device_id: fc6ab062501184a599762c445fa1c691
        entity_id: switch.plug_tv_bedroom
        domain: switch
      action_button_down_long:
      - service: scene.turn_on
        target:
          entity_id: scene.night
        metadata: {}
      action_button_down_double:
      - service: media_player.toggle
        data: {}
        target:
          entity_id: media_player.tv_bedroom
      button_up_double_press: true
      button_down_double_press: true
      helper_double_press_delay: 1000
- id: '1675625526304'
  alias: Kontroll Hall
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1812.yaml
    input:
      integration: ZHA
      controller_device: 04ce33caec348a593905d01720bebabe
      action_button_short:
      - service: alarm_control_panel.alarm_disarm
        data: {}
        target:
          entity_id: alarm_control_panel.alarmo
      helper_last_controller_event: input_text.controller_helper_hallway
- id: '1675782176107'
  alias: Kontroll Matilda Sovrum
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      integration: ZHA
      controller_device: 82d9af544c167ca030123651191d08c7
      helper_last_controller_event: input_text.controller_helper_matilda_bedroom
      button_down_long_max_loop_repeats: 100
      button_up_long_max_loop_repeats: 100
      button_down_long_loop: true
      button_up_long_loop: true
      action_button_up_long:
      - service: media_player.volume_up
        data: {}
        target:
          entity_id: media_player.tv_living_room
      action_button_down_long:
      - service: media_player.volume_down
        data: {}
        target:
          entity_id: media_player.tv_living_room
- id: '1675933105028'
  alias: Persistent notifikation - Otillgängliga entiteter
  description: Skapa persistent notifikation om otillgängliga enheter, avvisa om inga.
  trigger:
  - platform: state
    entity_id: sensor.unavailable_entities
    attribute: entity_id
    to:
  condition:
  - condition: template
    value_template: "{{ is_number(trigger.from_state.state)\n    and is_number(trigger.to_state.state)
      }}\n"
  action:
  - if:
    - condition: numeric_state
      entity_id: sensor.unavailable_entities
      below: 1
    then:
    - service: persistent_notification.dismiss
      data:
        notification_id: unavailable_entities
    else:
    - service: persistent_notification.create
      data:
        notification_id: unavailable_entities
        title: "{{ \"Otillgängliga entiteter (\" ~ states(\"sensor.unavailable_entities\")
          ~ \")\" }} \n"
        message: "{% set ns = namespace(result=[]) %} {% for s in expand(state_attr('sensor.unavailable_entities',
          'entity_id')) %}\n  {% set ns.result = ns.result + [\n      device_attr(s.entity_id,
          \"name\") ~ \"|\" ~ device_id(s.entity_id) ~ \"|- **\" ~ s.name ~ \"**\\n\"\n
          \     ~ \"  - *entity_id*: \" ~ s.entity_id ~ \"\\n\"\n      ~ \"  - *state*:
          \" ~ s.state ~ \"\\n\"\n    ]\n  %}\n{% endfor %}\n{% set ns.result = ns.result
          | sort %} {% set lastdev = namespace( id=\"\" ) %} {% set tarr = ns.result
          %} {% set ns.result = [] %} {% for item in tarr %}\n  {% set dev = namespace(
          id=\"\" ) %}\n  {% set entity = namespace( data=\"\" ) %}\n  {% set dev.id
          = item.split(\"|\")[1] %}\n  {% set entity.data = item.split(\"|\")[2] %}\n
          \ {% if lastdev.id != dev.id %}\n    {% if dev.id != 'None' %}\n      {%
          set ns.result = ns.result + [ \"**<a href=\\\"/config/devices/device/\"
          ~ dev.id ~ \"\\\">\" ~ device_attr(dev.id, \"name\") ~ \"</a>**\" ] %}\n
          \   {% else %}\n      {% set ns.result = ns.result + [ \"**Icke-enhetsentiteter**\"
          ] %}\n    {% endif %}\n    {% set lastdev.id = dev.id %}\n  {% endif %}\n
          \ {% set ns.result = ns.result + [ entity.data ] %}\n{% endfor %} {{ ns.result
          | join('\\n') }}\n"
  mode: restart
- id: '1678739259510'
  alias: Volymkontroll Vardagsrum
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1744.yaml
    input:
      integration: ZHA
      controller_device: 0eb1f091144c535885b9f93bcdf86169
      helper_last_controller_event: input_text.controller_helper_living_room_volume
      action_click_short: []
      action_click_double: []
      action_rotate_left: []
      action_rotate_right: []
      helper_debounce_delay: 100
- id: '1678740188806'
  alias: Hook - Media Player - TV Vardagsrum
  description: ''
  use_blueprint:
    path: EPMatt/media_player.yaml
    input:
      controller_model: IKEA E1744 SYMFONISK Rotary Remote
      media_player: media_player.tv_living_room
      controller_device: 0eb1f091144c535885b9f93bcdf86169
      volume_steps_long: 100
