---
# This sensor keeps track of the ATM10 version
#

sensor:
  - unique_id: a86a01ef-3931-44e7-8f84-850fd770a7b1
    state: >
      {% set motd = states('sensor.atm10_motd') %}
      {% set version = motd | regex_findall_index('[0-9]+\.[0-9]+') %}
      {{ version }}
