---
# This sensor keeps track of how many lights are on
#

sensor:
  - unique_id: a7f5dc10-973a-4f44-883b-5a774ec21695
    state_class: "measurement"
    state: >
      {% set ns = namespace(on_lights=0) %}
      {% set light_groups = [
          'light.all_aleas_room',
          'light.all_bathroom',
          'light.all_bedroom',
          'light.all_conservatory',
          'light.all_elinas_room',
          'light.all_entrance',
          'light.all_hallway',
          'light.all_kitchen',
          'light.all_living_room',
          'light.all_outside_front',
          'light.all_toilet'
        ]
      %}
      {% for group in light_groups %}
        {% set entities = state_attr(group, 'entity_id') %}
        {% if entities is not none %}
          {% for light in entities if is_state(light, 'on') %}
            {% set ns.on_lights = ns.on_lights + 1 %}
          {% endfor %}
        {% endif %}
      {% endfor %}
      {{ ns.on_lights }}