---
# Sensor to track premise entities
#

sensor:
  - unique_id: 0595b6ee-9fdd-4e89-bbdb-d22cec54618f
    state: >
      {% set entities = state_attr(this.entity_id,'entity_id') %}
      {{ entities|count if entities != none else none }}
    state_class: measurement
    attributes:
      entity_id: >
        {%- set data = namespace(entities=[]) -%}
        {% for entity in states %}
            {% if entity.entity_id|regex_search('^.*\.lokalen_.*$') %}
                {%- set data.entities = data.entities + [entity.entity_id] -%}
            {% endif %}
        {% endfor %}
        {{data.entities|list}}
