---
# This sensor keeps track of how many speakers are on
#

sensor:
  - unique_id: 17bc82f4-f9b0-4a06-9502-8f5fc763e177
    state_class: "measurement"
    unit_of_measurement: "högtalare"
    state: "{{expand(state_attr('media_player.speakers', 'entity_id'))| selectattr('state','in',['playing','buffering'])|map(attribute='entity_id')|list|count}}"
