---
# Sensor to track unavailable entities
#
# https://github.com/jazzyisj/unavailable-entities-sensor
#

sensor:
  - unique_id: 22e44867-57b9-4b45-aefb-41a889aaf837
    icon: "{{ iif(states(this.entity_id)|int(-1) > 0,'mdi:alert-circle','mdi:check-circle') }}"
    state: >
      {% set entities = state_attr(this.entity_id,'entity_id') %}
      {{ entities|count if entities != none else none }}
    state_class: measurement
    attributes:
      entity_id: >
        {# How long the entity has to be unavailable #}
        {% set ignore_seconds = 60 %}

        {# Ignore entities specified in the group "ignored_unavailable_entities" #}
        {% set ignored_entities = state_attr('group.ignored_unavailable_entities','entity_id')|list %}

        {# Ignore entities from google wifi #}
        {% set ignored_integration_entities = integration_entities('googlewifi')|list %}

        {# Ignore entities from NS Panel Hallway #}
        {% set ignored_device_entities = device_entities('a4fab9dadf4f2179b4f024d3d3d0fdf9')|list %}

        {# Ignore entities from NS Panel Living room #}
        {% set ignored_device_entities = ignored_device_entities|list + device_entities('1d834a32216cb87c3c19e81fcffafd7d')|list %}

        {# Combine all ignored entities arrays #}
        {% set ignored = ignored_entities + ignored_integration_entities + ignored_device_entities %}

        {% set ignore_ts = (now().timestamp() - ignore_seconds)|as_datetime %}

        {% set entities = states|rejectattr('domain','eq','group')
            |rejectattr('last_changed','ge',ignore_ts)
            |selectattr('state','in',['unavailable','unknown']) %}

        {% if ignored != none %}
          {% set entities =  entities|rejectattr('entity_id','in',ignored) %}
        {% endif %}

        {{ entities|map(attribute='entity_id')|list }}
