---
# This binary sensor is turned on when the washing machine is running
#

binary_sensor:
  - unique_id: "134b3946-ae3e-476d-b500-c845c13396ae"
    delay_off:
      seconds: 20
    state: >
      {{ states('sensor.plug_washing_machine_active_power')|float|default(0) > 0 }}
