---
# Monitor system temp
#

sensor:
  unique_id: "e9c4025d-179f-4007-a126-7294e3c6950c"
  command: "cat /sys/class/thermal/thermal_zone4/temp"
  scan_interval: 60
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(2)  }}"
