---
# https://github.com/Blackymas/NSPanel_HA_Blueprint
# This panel sits in the living room
#
# https://github.com/psvanstrom/esphome-p1reader
#

substitutions:

  ###### CHANGE ME START ######

  device_name: "ns_panel_living_room"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  # nextion_update_url: "http://192.168.86.22:8123/local/nspanel/nspanel_eu.tft"  # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft"  # URL to Github

  ##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
